@echo off
echo ....SCRIPT PARA CREAR MAQUINA CON SO DE 64BITS...
echo CREANDO LA MAQUINA...
vboxmanage createvm --name ubuntuExamen --ostype "Ubuntu_64" --register
echo CONFIGURANDO RED...
#vboxmanage modifyvm Ubuntu --nic1 bridged --bridgeadapter1 enp0s3
vboxmanage modifyvm ubuntuExamen --bridgeadapter1 enp0s3
vboxmanage modifyvm ubuntuExamen --nic1 bridged
echo CONFIGURANDO MEMORIA...
vboxmanage modifyvm ubuntuExamen --memory 2048
echo CREANDO DISCO DURO...
vboxmanage createhd --filename ubuntuserver18_64.vdi --size 50000 --format VDI
vboxmanage storagectl ubuntuExamen --name "SATA Controller" --add sata --controller IntelAhci
vboxmanage storageattach ubuntuExamen --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium ubuntuserver18_64.vdi
vboxmanage storagectl ubuntuExamen --name "IDE Controller" --add ide --controller PIIX4
echo RELACIONANDO DISCO DURO CON LA IMAGEN QUE CONTIENE EL SO...
vboxmanage storageattach ubuntuExamen --storagectl "IDE Controller" --port 1 --device 0 --type dvddrive --medium ubuntu-18.04.2-live-server-amd64.iso